version: "3"

services:
  grafana:
    image: grafana/grafana:9.5.6
    user: 1000:1000
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres
    security_opt:
      - no-new-privileges:true
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
  postgres:
    build:
      context: ./
      dockerfile: ./docker/postgres.Dockerfile
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=h10
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

volumes:
  grafana_data:
  postgres_data: